# -*- coding: utf-8 -*-
"""Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y7RQikWbPuZStykSjT6IJLb1RPy_JZLL
"""

# Commented out IPython magic to ensure Python compatibility.
#Importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
# %matplotlib inline

from datetime import date
import time
from pandas import Timestamp

path = "/content/mario_final.csv"

#Reading the excel file
data = pd.read_csv(path)

data.shape

data.head(5)

data.drop(["UserName","max_date","Location","User Profile Description","Tweets"], axis = 1, inplace=True)

data.head(2)

data = data.rename(columns={'Tweets_perc':'perc','Days past last tweet date': 'days', 'User Followers': 'Followers','Max Polarity':'polarity'})

data.head(1)

data.isna().sum()



from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import scipy.stats as stats

scaled_df = stats.zscore(data)

scaled_df

X = scaled_df[["Tweet_perc","days","maxpolarity","Followers"]]

#Importing KMeans from sklearn
from sklearn.cluster import KMeans

wcss=[]
for i in range(1,11):
    km=KMeans(n_clusters=i)
    km.fit(X)
    wcss.append(km.inertia_)

#The elbow curve
plt.figure(figsize=(12,6))
plt.plot(range(1,11),wcss)
plt.plot(range(1,11),wcss, linewidth=2, color="red", marker ="8")
plt.xlabel("K Value")
plt.xticks(np.arange(1,11,1))
plt.ylabel("WCSS")
plt.show()

#Taking 5 clusters
km1=KMeans(n_clusters=5)
#Fitting the input data
km1.fit(X)
#predicting the labels of the input data
y=km1.predict(X)
#adding the labels to a column named label
scaled_df["label"] = y
#The new dataframe with the clustering done
scaled_df.head(10)



from mpl_toolkits import mplot3d

df1 = scaled_df[scaled_df.label==0]
df2 = scaled_df[scaled_df.label==1]
df3 = scaled_df[scaled_df.label==2]
df4 = scaled_df[scaled_df.label==3]
df5 = scaled_df[scaled_df.label==4]

plt.scatter(df1.Followers,df1['maxpolarity'],color='green')
plt.scatter(df2.Followers,df2['maxpolarity'],color='red')
plt.scatter(df3.Followers,df3['maxpolarity'],color='black')
plt.scatter(df4.Followers,df4['maxpolarity'],color='yellow',label='yellow')
plt.scatter(df5.Followers,df5['maxpolarity'],color='orange')
plt.scatter(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color='purple',marker='*')


plt.legend()

