# -*- coding: utf-8 -*-
"""Scrap Location_Ayush .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kZr1KFMhPR9HjR_myb1Jx1xC8-tlW6-m
"""

import pandas as pd
import snscrape.modules.twitter as sntwitter
import itertools
from textblob import TextBlob
from google.colab import files

pip install snscrape

"""**Fifa 24 Product :**"""

loc = '40.730610,-73.935242, 100km'
fifa_ny = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 60000))
fifa_ny['Tweet_Created_Date'] = pd.to_datetime(fifa_ny['date']).dt.date
fifa_ny['Location'] ='New York' 
fifa_v1=fifa_ny[['date','Tweet_Created_Date','content','username','Location']]
fifa_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location']
print(fifa_v1.head(5))
print(fifa_v1.shape)

product='fifa'
location='LA'
loc = '34.052235,-118.243683, 100km'
fifa_LA = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 50000))
fifa_LA['Tweet_Created_Date'] = pd.to_datetime(fifa_LA['date']).dt.date
fifa_LA['Location'] ='{}'.format(location) 
fifa_LA_v1=fifa_LA[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
fifa_LA_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
fifa_LA_v1.shape

product='fifa'
location='Chicago'
loc = '41.881832,-87.623177, 100km'
fifa_Chic = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 40000))
fifa_Chic['Tweet_Created_Date'] = pd.to_datetime(fifa_Chic['date']).dt.date
fifa_Chic['Location'] ='{}'.format(location) 
fifa_Chic_v1=fifa_Chic[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
fifa_Chic_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
fifa_Chic_v1.tail(5)

"""**Starting from here**"""

product='mario'
location='Indianapolis'
loc = '39.791000,-86.148003, 100km'
fifa_Ind = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-20 (fifa OR football) geocode:"{}"'.format(loc)).get_items(), 10000))
fifa_Ind['Tweet_Created_Date'] = pd.to_datetime(fifa_Ind['date']).dt.date
fifa_Ind['Location'] ='{}'.format(location) 
fifa_Ind_v1=fifa_Ind[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
fifa_Ind_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
fifa_Ind_v1.tail(5)

#added to bigger query
product='fifa'
location='Columbus'
loc = '39.983334,-82.983330, 100km'
fifa_Col = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-20 (fifa OR football) geocode:"{}"'.format(loc)).get_items(), 10000))
fifa_Col['Tweet_Created_Date'] = pd.to_datetime(fifa_Col['date']).dt.date
fifa_Col['Location'] ='{}'.format(location) 
fifa_Col_v1=fifa_Col[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
fifa_Col_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
fifa_Col_v1.tail(5)

#added to bigger query
location='FortWorth'
loc = '32.768799,-97.309341, 100km'
fifa_FW = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-20 (fifa OR football) geocode:"{}"'.format(loc)).get_items(), 10000))
fifa_FW['Tweet_Created_Date'] = pd.to_datetime(fifa_FW['date']).dt.date
fifa_FW['Location'] ='{}'.format(location) 
fifa_FW_v1=fifa_FW[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
fifa_FW_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
fifa_FW_v1.tail(5)

#added to bigger query
location='Austin'
loc = '30.266666,-97.733330, 100km'
fifa_Austin = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-20 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 15000))
fifa_Austin['Tweet_Created_Date'] = pd.to_datetime(fifa_Austin['date']).dt.date
fifa_Austin['Location'] ='{}'.format(location) 
fifa_Austin_v1=fifa_Austin[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
fifa_Austin_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns

location='Jacksonville'
loc = '30.332184,-81.655647, 100km'
fifa_Jack = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-20 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 15000))
fifa_Jack['Tweet_Created_Date'] = pd.to_datetime(fifa_Jack['date']).dt.date
fifa_Jack['Location'] ='{}'.format(location) 
fifa_Jack_v1=fifa_Jack[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
fifa_Jack_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns

fifa_Austin_v1.shape
fifa_Jack_v1.shape

fifa_Austin_v1.empty

location='Indianapolis'
loc = '39.791000,-86.148003, 100km'
fifa_Ind = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_Ind.empty==False:
  fifa_Ind['Tweet_Created_Date'] = pd.to_datetime(fifa_Ind['date']).dt.date
  fifa_Ind['Location'] ='{}'.format(location) 
  fifa_Ind_v1=fifa_Ind[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_Ind_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_Ind_v1.shape)
else:
  print('Dataframe is empty')

location='Columbus'
loc = '39.983334,-82.983330, 100km'
fifa_Col = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_Col.empty==False:
  fifa_Col['Tweet_Created_Date'] = pd.to_datetime(fifa_Col['date']).dt.date
  fifa_Col['Location'] ='{}'.format(location) 
  fifa_Col_v1=fifa_Col[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_Col_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_Col_v1.shape)
else:
  print('Dataframe is empty')

location='FortWorth'
loc = '32.768799,-97.309341, 100km'
fifa_FW = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_FW.empty==False:
  fifa_FW['Tweet_Created_Date'] = pd.to_datetime(fifa_FW['date']).dt.date
  fifa_FW['Location'] ='{}'.format(location) 
  fifa_FW_v1=fifa_FW[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_FW_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_FW_v1.shape)
else:
  print('Dataframe is empty')

location='Austin'
loc = '30.266666,-97.733330, 100km'
fifa_Austin = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_Austin.empty==False:
  fifa_Austin['Tweet_Created_Date'] = pd.to_datetime(fifa_Austin['date']).dt.date
  fifa_Austin['Location'] ='{}'.format(location) 
  fifa_Austin_v1=fifa_Austin[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_Austin_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_Austin_v1.shape)
else:
  print('Dataframe is empty')

location='Jacksonville'
loc = '30.332184,-81.655647, 100km'
fifa_Jack = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_Jack.empty==False:
  fifa_Jack['Tweet_Created_Date'] = pd.to_datetime(fifa_Jack['date']).dt.date
  fifa_Jack['Location'] ='{}'.format(location) 
  fifa_Jack_v1=fifa_Jack[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_Jack_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_Jack_v1.shape)
else:
  print('Dataframe is empty')

location='San Jose'
loc = '37.335480,-121.893028, 100km'
fifa_SJ = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_SJ.empty==False:
  fifa_SJ['Tweet_Created_Date'] = pd.to_datetime(fifa_SJ['date']).dt.date
  fifa_SJ['Location'] ='{}'.format(location) 
  fifa_SJ_v1=fifa_SJ[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_SJ_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_SJ_v1.shape)
else:
  print('Dataframe is empty')

location='Dallas'
loc = '32.779167,-96.808891, 100km'
fifa_Dallas = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_Dallas.empty==False:
  fifa_Dallas['Tweet_Created_Date'] = pd.to_datetime(fifa_Dallas['date']).dt.date
  fifa_Dallas['Location'] ='{}'.format(location) 
  fifa_Dallas_v1=fifa_Dallas[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_Dallas_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_Dallas_v1.shape)
else:
  print('Dataframe is empty')

location='Bronx'
loc = '40.837048,-73.865433, 100km'
fifa_Bronx = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_Bronx.empty==False:
  fifa_Bronx['Tweet_Created_Date'] = pd.to_datetime(fifa_Bronx['date']).dt.date
  fifa_Bronx['Location'] ='{}'.format(location) 
  fifa_Bronx_v1=fifa_Bronx[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_Bronx_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_Bronx_v1.shape)
else:
  print('Dataframe is empty')

location='SanDiego'
loc = '32.715736,-117.161087, 100km'
fifa_SD = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_SD.empty==False:
  fifa_SD['Tweet_Created_Date'] = pd.to_datetime(fifa_SD['date']).dt.date
  fifa_SD['Location'] ='{}'.format(location) 
  fifa_SD_v1=fifa_SD[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_SD_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_SD_v1.shape)
else:
  print('Dataframe is empty')

location='SanAntonio'
loc = '29.424349,-98.491142, 100km'
fifa_SA = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (fifa OR football OR PlayStation OR PS4 OR PS5 OR PS3 OR PS2 OR PS1 OR Messi OR Ronaldo) geocode:"{}"'.format(loc)).get_items(), 30000))
if fifa_SA.empty==False:
  fifa_SA['Tweet_Created_Date'] = pd.to_datetime(fifa_SA['date']).dt.date
  fifa_SA['Location'] ='{}'.format(location) 
  fifa_SA_v1=fifa_SA[['date','Tweet_Created_Date','content','username','Location']] # picking the imp ones
  fifa_SA_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location'] # renaming columns
  print(fifa_SA_v1.shape)
else:
  print('Dataframe is empty')

fifa_SA_v1.head(5)

"""**Importing csv file and converting into df**"""

from google.colab import files
fifa_ny_la_chic = files.upload()

import io
rest = pd.read_csv(io.BytesIO(fifa_ny_la_chic['rest.csv']))

#rest=rest.iloc[:,1:]
rest.head(2)

"""**Dataframe concatenation**"""

fifa = pd.concat([fifa_v1,fifa_LA_v1,fifa_Chic_v1,fifa_Ind_v1,fifa_Col_v1,fifa_FW_v1,fifa_Austin_v1,fifa_Jack_v1,fifa_SJ_v1,fifa_Dallas_v1,fifa_Bronx_v1,fifa_SD_v1,fifa_SA_v1], axis=0)
fifa.shape

fifa_full = pd.concat([fifa_13cities,fifa_rest])
fifa_full.shape

fifa_full['Location'].value_counts()

"""**Csv download using dataframe 'fifa'**"""

keyword='d10_df'
d10_df.to_csv('{}.csv'.format(keyword))
files.download('{}.csv'.format(keyword))

"""**Add polarity:**"""

import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

fifa_full['scores'] = fifa_full['Tweet'].apply(lambda review: sid.polarity_scores(review))
fifa_full['compound']  = fifa_full['scores'].apply(lambda score_dict: score_dict['compound'])
fifa_full.head()

fifa_full['compound']  = fifa_full['scores'].apply(lambda score_dict: score_dict['compound'])

fifa_full.head(5)

fifa_full.Tweet_Created_Date.min()

"""**Checking and eliminating null values in data frame**"""

fifa_full.shape

fifa_full.isnull().sum()

fifa_full_v1=fifa_full[~fifa_full.UserName.isna()]
fifa_full_v1.shape

"""**Creating 4 categories - PP, PN, NP, NN polarity tweets** """

# PP
f1=fifa_full_v1[(fifa_full_v1.compound>0) & (fifa_full_v1.Tweet_Created_Date<'2022-10-01')]
f2=fifa_full_v1[(fifa_full_v1.compound>0) & (fifa_full_v1.Tweet_Created_Date>='2022-10-01')]
f3=pd.DataFrame(f1['UserName'])
fifa_pos_pos_usr=f3.merge(f2['UserName'],how='inner',on='UserName')
fifa_pos_pos_usr.drop_duplicates(inplace=True)
print(fifa_pos_pos_usr.head(2))
print(fifa_pos_pos_usr.shape)

names=list(fifa_pos_pos_usr['UserName'])
f1=f1[f1['UserName'].isin(names)]
f2=f2[f2['UserName'].isin(names)]
frames = [f1,f2]

fifa_pos_pos=pd.concat(frames)
print(fifa_pos_pos.shape)

# PN
f1=fifa_full_v1[(fifa_full_v1.compound>0) & (fifa_full_v1.Tweet_Created_Date<'2022-10-01')]
f2=fifa_full_v1[(fifa_full_v1.compound<0) & (fifa_full_v1.Tweet_Created_Date>='2022-10-01')]
f3=pd.DataFrame(f1['UserName'])
fifa_pos_neg_usr=f3.merge(f2['UserName'],how='inner',on='UserName')
fifa_pos_neg_usr.drop_duplicates(inplace=True)
print(fifa_pos_neg_usr.head(2))
print(fifa_pos_neg_usr.shape)

names=list(fifa_pos_neg_usr['UserName'])
f1=f1[f1['UserName'].isin(names)]
f2=f2[f2['UserName'].isin(names)]
frames = [f1,f2]

fifa_pos_neg=pd.concat(frames)
print(fifa_pos_neg.shape)

# NN
f1=fifa_full_v1[(fifa_full_v1.compound<0) & (fifa_full_v1.Tweet_Created_Date<'2022-10-01')]
f2=fifa_full_v1[(fifa_full_v1.compound<0) & (fifa_full_v1.Tweet_Created_Date>='2022-10-01')]
f3=pd.DataFrame(f1['UserName'])
fifa_neg_neg_usr=f3.merge(f2['UserName'],how='inner',on='UserName')
fifa_neg_neg_usr.drop_duplicates(inplace=True)
print(fifa_neg_neg_usr.head(2))
print(fifa_neg_neg_usr.shape)

names=list(fifa_neg_neg_usr['UserName'])
f1=f1[f1['UserName'].isin(names)]
f2=f2[f2['UserName'].isin(names)]
frames = [f1,f2]

fifa_neg_neg=pd.concat(frames)
print(fifa_neg_neg.shape)

# NP
f1=fifa_full_v1[(fifa_full_v1.compound<0) & (fifa_full_v1.Tweet_Created_Date<'2022-10-01')]
f2=fifa_full_v1[(fifa_full_v1.compound>0) & (fifa_full_v1.Tweet_Created_Date>='2022-10-01')]
f3=pd.DataFrame(f1['UserName'])
fifa_neg_pos_usr=f3.merge(f2['UserName'],how='inner',on='UserName')
fifa_neg_pos_usr.drop_duplicates(inplace=True)
print(fifa_neg_pos_usr.head(2))
print(fifa_neg_pos_usr.shape)

names=list(fifa_neg_pos_usr['UserName'])
f1=f1[f1['UserName'].isin(names)]
f2=f2[f2['UserName'].isin(names)]
frames = [f1,f2]

fifa_neg_pos=pd.concat(frames)
print(fifa_neg_pos.shape)

#Final Population for FIFA24:
 
fifa_final=pd.concat([fifa_neg_pos,fifa_pos_pos])
print(fifa_final.shape)
print(fifa_final.head(2))

f1=fifa_final.groupby(by='UserName').Tweet_Created_Date.count()
f1=pd.DataFrame(f1)
f1.reset_index(inplace=True)
f1 = f1.rename(columns = {'index':'UserName','Tweet_Created_Date':'Tweets'})
print(f1.head(2))
print(f1.shape)

f2=fifa_final.groupby(by='UserName').agg({'Tweet_Created_Date' :'max', 'compound' : 'max'})
f2.columns = ['max_date','maxpolarity']
f2=f2.reset_index()
print(f2.head(2))

f3=f1.merge(f2,how='left',on='UserName')
print(f3.head(2))
print(f3.shape)

f20=fifa_full_v1[['UserName','Location']].drop_duplicates()
f20['rank'] = f20.groupby('UserName')['Location'].rank(method='first')
f20=f20[f20['rank']==1]
f20.shape

fifa_final_v1=f3.merge(f20[['UserName','Location']],how='left', on='UserName')
print(fifa_final_v1.head(2))
print(fifa_final_v1.shape)

"""**Removing Duplicates at Overall Level**"""

fifa_full_v1['rank'] = fifa_full_v1.groupby('Tweet')['Location'].rank(method='first')
fifa_full_v1.head(2)

fifa_full_v1=fifa_full_v1[fifa_full_v1['rank']==1]
print(fifa_full_v1.shape)

"""*For word cloud:*"""

fifa_full_v1['rank'] = fifa_full_v1.groupby('Tweet')['Location'].rank(method='first')
print(fifa_full_v1.head(2))
print(fifa_full_v1.shape)

fifa_full_v1=fifa_full_v1[fifa_full_v1['rank']==1]
print(fifa_full_v1.shape)

abc=fifa_full_v1[['Tweet','Location','compound']].drop_duplicates()
print(abc.shape)
print(fifa_full_v1[['Tweet','Location','compound']].shape)
fifa_neg_final=fifa_full_v1[['Tweet','Location','compound']]
fifa_neg_final=fifa_neg_final[fifa_neg_final['compound']<0]
print(fifa_neg_final.shape)

"""**Not required** : Performing validation to identify target audience"""

# Not required
f1=fifa_pos.groupby(by='UserName').Tweet_Created_Date.count()
f1=pd.DataFrame(f1)
f1.reset_index(inplace=True)
f1 = f1.rename(columns = {'index':'UserName','Tweet_Created_Date':'Tweets'})
f1=f1[f1.Tweets>1]
print(f1.head(2))
print(f1.shape)

f2=fifa_pos.groupby(by='UserName').agg({'Tweet_Created_Date' :['min', 'max'], 'compound' : 'max'})
f2.columns = ['min_date', 'max_date', 'maxpolarity']
f2=f2.reset_index()
print(f2.head(2))

f3=f1.merge(f2,how='left',on='UserName')
print(f3.head(2))
print(f3.shape)

"""*Removing cases where multiple location is found per user*"""

f20=fifa_pos[['UserName','Location']].drop_duplicates()
f20['rank'] = f20.groupby('UserName')['Location'].rank(method='first')
f20=f20[f20['rank']==1]
f20.shape

fifa_tar=f3[(f3['max_date'] >='2022-10-01') & (f3['min_date'] <'2022-10-01')]
fifa_tar=fifa_tar.merge(f20[['UserName','Location']],how='left', on='UserName')
print(fifa_tar.head(2))
print(len(fifa_tar))

"""<u>**Product 3</u>** - Chain of thorns

**<u>Keyword</u>** - Novel OR ChainOfThorns OR Reading OR (Cordelia Carstairs) OR (Young Adult Fiction) OR YoungAdultFiction OR (Simon & Schuster) OR Thriller OR Author OR FantasyFiction OR (Fantasy Fiction) OR (Chain of Thorns) OR (Cassandra Clare) OR Cassandra OR Shadowhunters OR (Chain of Iron) OR (Chain of Gold)
"""

loc = '40.730610,-73.935242, 100km'
adidas_ny = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (Novel OR ChainOfThorns OR Reading OR (Cordelia Carstairs) OR (Young Adult Fiction) OR YoungAdultFiction OR (Simon & Schuster) OR Thriller OR Author OR FantasyFiction OR (Fantasy Fiction) OR (Chain of Thorns) OR (Cassandra Clare) OR Cassandra OR Shadowhunters OR (Chain of Iron) OR (Chain of Gold)) geocode:"{}"'.format(loc)).get_items(), 60000))
adidas_ny['Tweet_Created_Date'] = pd.to_datetime(adidas_ny['date']).dt.date
adidas_ny['Location'] ='New York' 
adidas_v1=adidas_ny[['date','Tweet_Created_Date','content','username','Location']]
adidas_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location']
print(adidas_v1.head(5))
print(adidas_v1.shape)

"""**<u>Product 4**</u> - Blink 182

**<u>Keyword</u>** - Music OR (MCA Records) OR (Blink 182) OR Blink-182 OR Rockband OR Concert OR (Mark Hoppus) OR (Tom DeLonge) OR (Travis Barker) OR (Punk rock) OR (Pop music) OR (Pop-punk) OR (Alternative rock) OR (Skate punk)
"""

loc = '40.730610,-73.935242, 100km'
adidas_ny = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (Music OR (MCA Records) OR (Blink 182) OR Blink-182 OR Rockband OR Concert OR (Mark Hoppus) OR (Tom DeLonge) OR (Travis Barker) OR (Punk rock) OR (Pop music) OR (Pop-punk) OR (Alternative rock) OR (Skate punk)) geocode:"{}"'.format(loc)).get_items(), 60000))
adidas_ny['Tweet_Created_Date'] = pd.to_datetime(adidas_ny['date']).dt.date
adidas_ny['Location'] ='New York' 
adidas_v1=adidas_ny[['date','Tweet_Created_Date','content','username','Location']]
adidas_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location']
print(adidas_v1.head(5))
print(adidas_v1.shape)

"""**<u>Product 5</u>** - Samsung Galaxy S23

**<u>Keyword</u>** -  (Samsung Galaxy S23) OR Android OR Samsung OR Mobile OR Phone OR (Samsung Galaxy) OR (hate iPhone)
"""

loc = '40.730610,-73.935242, 100km'
adidas_ny = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 ((Samsung Galaxy S23) OR Android OR Samsung OR Mobile OR Phone OR (Samsung Galaxy) OR (hate iPhone)) geocode:"{}"'.format(loc)).get_items(), 60000))
adidas_ny['Tweet_Created_Date'] = pd.to_datetime(adidas_ny['date']).dt.date
adidas_ny['Location'] ='New York' 
adidas_v1=adidas_ny[['date','Tweet_Created_Date','content','username','Location']]
adidas_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location']
print(adidas_v1.head(5)) 
print(adidas_v1.shape)

"""**<u>Product 6</u>** - DSM bio-based vitamin A

**<u>Keyword</u>** - DSM OR Diet OR (Health Supplement) OR Vitamin OR bio-based OR Health OR (Joerg von-Allmen)
"""

loc = '40.730610,-73.935242, 100km'
adidas_ny = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'lang:en since:2022-01-01 until:2022-11-25 (DSM OR Diet OR (Health Supplement) OR Vitamin OR bio-based OR Health OR (Joerg von-Allmen)) geocode:"{}"'.format(loc)).get_items(), 60000))
adidas_ny['Tweet_Created_Date'] = pd.to_datetime(adidas_ny['date']).dt.date
adidas_ny['Location'] ='New York' 
adidas_v1=adidas_ny[['date','Tweet_Created_Date','content','username','Location']]
adidas_v1.columns=['Date','Tweet_Created_Date','Tweet','UserName','Location']
print(adidas_v1.head(5)) 
print(adidas_v1.shape)

"""**Additional Attributes - User Followers, Joining date and description**"""

import tweepy
  
# assign the values accordingly
consumer_key = 'PNVeKusZOpo3XTLlvH0k2oHtQ'
consumer_secret = 'XksFog5efD9UIKR4n2bbrpg38lloUW7SKnxAsFd7ZeEdYe4FJF'
access_token = '1020155065653329920-bG6SCYIn5K1PwbOHNi3nSg2hL0NGEo'
access_token_secret = '0kRj7RfSWymKgeLle7DAcOdUoQxwghRRMVsTIljDhQ3rB'
  
# authorization of consumer key and consumer secret
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
  
# set access to user's access key and access secret 
auth.set_access_token(access_token, access_token_secret)
  
# calling the api 
api = tweepy.API(auth,wait_on_rate_limit=True)

# Ignore
import time
userfollowers=[]
i=0
while i<2000:
  usernames=fifa_tar.UserName.values[i:(i+100)]

#usercreatedat=[]
#userdesc=[]

  for j in usernames:
    try:
      user = api.get_user(j)
  #usercreatedat.append(user.created_at)
      userfollowers.append(user.followers_count)
  #time.sleep(1) 
    except:
      pass
  i=i+100
  #userdesc.append(user.description)
#fifa['UserCreatedAt']=usercreatedat
#fifa['UserFollowers']=userfollowers
#fifa['UserDescription']=userdesc
  
print(userfollowers)

rest.head(2)

# Manual
import time
f10={}
d10={}
usernames=rest.UserName.values[0:732]
for j in usernames:
  try:
    user = api.get_user(j)
    #usercreatedat[j]=user.created_at
    f10[j]=user.followers_count
    d10[j]=user.description
  except:
    pass
#print(usercreatedat)
print(len(f10))
print(len(d10))

# Manual
import time
f3=[]
c3=[]
d3=[]
usernames=fifa_tar.UserName.values[0:4]
for j in usernames:
  try:
    user = api.get_user(j)
    c3.append(user.created_at)
    f3.append(user.followers_count)
    d3.append(user.description)
  except:
    pass
print(c3)

f10_df=pd.DataFrame.from_dict(f10,orient='index')
f10_df.reset_index(inplace=True)
f10_df = f10_df.rename(columns = {'index':'UserName', '0': 'UserDesc'})
f10_df.head(2)

usr_desc=pd.concat([d1_df,d2_df,d3_df,d4_df,d5_df,d6_df,d7_df,d8_df,d9_df,d10_df])
usr_desc.drop_duplicates(inplace=True)
print(usr_desc.head(2))
print(usr_desc.shape)

fifa_final_fol=f3.merge(f10_df,how='left',on='UserName')
print(fifa_final_fol.head(5))
print(fifa_final_fol.shape)

fifa_tar_final.isna().sum()

#fifa_tar_final.columns=['UserName','Tweets','min_date','max_date','maxpolarity','Location','Followers','UserDesc']
#fifa_tar_final['Followers'].fillna(int(fifa_tar_final['Followers'].mean()), inplace=True)
fifa_tar_final.head(5)

fifa_tar.shape

"""*Visualize tweets month wise*"""

import datetime
fifa_pos['month']=pd.to_datetime(fifa_pos['Date']).dt.month
fifa_pos['year']=pd.to_datetime(fifa_pos['Date']).dt.year
fifa_pos['period']=fifa_pos['month'].astype(str) + "-" + fifa_pos['year'].astype(str)
fifa_pos['Tweet_Date'] = pd.to_datetime(fifa_pos['Date']).dt.date
fifa_pos.head(2)

import seaborn as sns
sns.set(rc={"figure.figsize":(8, 6)})
ax=sns.histplot(data=fifa_pos[fifa_pos['Date'] >='2022-01-01'],x='month',bins=11, color='orange',kde=False,stat='density')
sns.kdeplot(data=fifa_pos[fifa_pos['Date'] >='2022-01-01'], x='month', color='blue', ax=ax, linestyle="--")

"""*Time Series Trend on Sentiments*"""

import numpy as np
conditions = [
    (fifa_full_v1['compound'] > 0),
    (fifa_full_v1['compound'] ==0),
    (fifa_full_v1['compound'] < 0)
    ]
values = ['Positive', 'Neutral', 'Negative']
fifa_full_v1['Sentiment'] = np.select(conditions, values)
fifa_full_v1['month']=pd.to_datetime(fifa_pos['Tweet_Created_Date']).dt.month
fifa_full_v1.head(2)

fifa_trend=fifa_full_v1.groupby(by=['month','Sentiment']).compound.mean()
fifa_trend=pd.DataFrame(fifa_trend)
fifa_trend.reset_index(inplace=True)
#fifa_trend = fifa_trend.rename(columns = {'index':'UserName','Tweet_Created_Date':'Tweets'})
print(fifa_trend.head(5))
print(fifa_trend.shape)

fifa_trend_pos=fifa_trend[fifa_trend['Sentiment']=='Positive']
fifa_trend_neg=fifa_trend[fifa_trend['Sentiment']=='Negative']
print(fifa_trend_pos.shape)
print(fifa_trend_neg.shape)

import numpy as np
from matplotlib import pyplot as plt
plt.rcParams["figure.figsize"] = [14, 4]
plt.rcParams["figure.autolayout"] = True
f, axes = plt.subplots(1, 2)
sns.lineplot(data=fifa_trend_pos,x='month',y='compound',hue='Sentiment',ax=axes[0])
sns.lineplot(data=fifa_trend_neg,x='month',y='compound',hue='Sentiment',ax=axes[1])
plt.show()